################
# See:
# https://docs.travis-ci.com/user/getting-started/
################

################
# Use container-based infrastructure on Travis:
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
################

################
# Specify runtime and versions
# See: https://docs.travis-ci.com/user/customizing-the-build/#Specifying-Runtime-Versions
language: python
#python:
#- "2.7"
################

################
# Install dependencies:
install: "pip install -r requirements.txt"
################

################
# Set up the environment to run within the Travis VM (see the default packages it already has)
# Do this with 'env:' options
# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/environment-variables/

# And select how the builds will be run, how many, what language versions, etc.:
# 'matrix:' options
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

# And setup any exclusions or inclusions for the builds
# 'include:' or 'exclude:

# These within the 'matrix:' specification:

matrix:
  include:
  - python: "2.7"
    env: TEST_STYLE=1
  - python: "3.5"
    env: TEST_STYLE=1

################


################
# command to run tests
script: sh run_travis_tests.sh
################
