# use container-based infrastructure on Travis
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

language: python

env:
#  global:
#    - CGAT_TASK_STEPSIZE=100
  matrix:
    - TEST_STYLE=1

python:
- "2.7"
